### ISSUE TITLE
MLX75027

### ISSUE THREAD

**Issue by LCKway** [rzw2/mlx75027_config#1]
Hey, friend
Recently I want to do a flight time about MLX75027, I hope you can give me a little help.
thank you！

**Comment by rzw2** [comment]
Sure, what can I help you with?

**Comment by LCKway** [comment]
What kind of chip do you use for control?  FPGA or ARM chip

**Comment by LCKway** [comment]
How did you choose the light source? And how was the lens chosen?

**Comment by LCKway** [comment]
There is too little information about MLX75027 online. The only information I have now is the chip manual in your project. Can you provide me with information other than the chip manual?

**Comment by rzw2** [comment]
This blog post should hopefully answer some of your questions about Chip interface and illumination. https://medium.com/chronoptics-time-of-flight/indirect-time-of-flight-depth-camera-systems-design-52d4aa6416d0

Can Chronoptics contract design you a ToF depth camera?

**Comment by LCKway** [comment]
So you are a company specialized in TOF.
I'm sorry. I may not be able to pay you to help me design a plan.
Sorry to bother you.
But I still hope you can give me some resources about MLX75027 open source.

**Comment by rzw2** [comment]
Time-of-Flight camera's are a complex systems design, hopefully that blog post will get you started, there are some other design resources you should look at this information from Espros Photonics, https://www.espros.com/time-of-flight/ , also have a look at this introduction from Analog Devices as well. https://devblogs.microsoft.com/azure-depth-platform/time-of-flight-camera-system-overview/ 

Are there any particular questions about the MLX75027 sensor you have? Any sections of the datasheet you want further understanding about?

**Comment by rzw2** [comment]
And sorry I don't have any more documentation about the MLX75027 sensor.

**Comment by LCKway** [comment]
Thank you. You've really helped me a lot.
I have to leave the research on MLX75027 sensor for a while, I still have to learn the use of MIPI-CSI protocol.
You are using IMX8 soc as control. Can you show me the driver for the MLX75027 sensor

**Comment by rzw2** [comment]
MIPI-CSI is a very standard interface for image sensors, as for the IMX8 SoC device driver we modified an existing device driver for an image sensor.
